/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestRegionRouteImport } from './routes/request-region'
import { Route as IndexRouteImport } from './routes/index'

const RequestRegionRoute = RequestRegionRouteImport.update({
  id: '/request-region',
  path: '/request-region',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request-region': typeof RequestRegionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request-region': typeof RequestRegionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/request-region': typeof RequestRegionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/request-region'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/request-region'
  id: '__root__' | '/' | '/request-region'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestRegionRoute: typeof RequestRegionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-region': {
      id: '/request-region'
      path: '/request-region'
      fullPath: '/request-region'
      preLoaderRoute: typeof RequestRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestRegionRoute: RequestRegionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
